### ISSUE TITLE
Missing required parameter in input: "ApplicationId"

### ISSUE THREAD

**Issue by kolanos** [awslabs/aws-serverlessrepo-python#34]
When trying to run `sam publish -t packaged.yaml` to update an application that already exists I get the following error:

```
Traceback (most recent call last):
  File "/Users/kolanos/.virtualenvs/aws/lib/python3.7/site-packages/serverlessrepo/publish.py", line 45, in publish_application
    response = sar_client.create_application(**request)
  File "/Users/kolanos/.virtualenvs/aws/lib/python3.7/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/kolanos/.virtualenvs/aws/lib/python3.7/site-packages/botocore/client.py", line 635, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ConflictException: An error occurred (ConflictException) when calling the CreateApplication operation: Application with name NewRelic-log-ingestion already exists

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kolanos/.virtualenvs/aws/bin/sam", line 8, in <module>
    sys.exit(cli())
  File "/Users/kolanos/.virtualenvs/aws/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/kolanos/.virtualenvs/aws/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/kolanos/.virtualenvs/aws/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/kolanos/.virtualenvs/aws/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/kolanos/.virtualenvs/aws/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/kolanos/.virtualenvs/aws/lib/python3.7/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/Users/kolanos/.virtualenvs/aws/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/kolanos/.virtualenvs/aws/lib/python3.7/site-packages/samcli/lib/telemetry/metrics.py", line 96, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "/Users/kolanos/.virtualenvs/aws/lib/python3.7/site-packages/samcli/lib/telemetry/metrics.py", line 62, in wrapped
    return_value = func(*args, **kwargs)
  File "/Users/kolanos/.virtualenvs/aws/lib/python3.7/site-packages/samcli/commands/publish/command.py", line 54, in cli
    do_cli(ctx, template_file, semantic_version)  # pragma: no cover
  File "/Users/kolanos/.virtualenvs/aws/lib/python3.7/site-packages/samcli/commands/publish/command.py", line 77, in do_cli
    publish_output = publish_application(template_data)
  File "/Users/kolanos/.virtualenvs/aws/lib/python3.7/site-packages/serverlessrepo/publish.py", line 57, in publish_application
    sar_client.update_application(**request)
  File "/Users/kolanos/.virtualenvs/aws/lib/python3.7/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/kolanos/.virtualenvs/aws/lib/python3.7/site-packages/botocore/client.py", line 608, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/Users/kolanos/.virtualenvs/aws/lib/python3.7/site-packages/botocore/client.py", line 656, in _convert_to_request_dict
    api_params, operation_model)
  File "/Users/kolanos/.virtualenvs/aws/lib/python3.7/site-packages/botocore/validate.py", line 297, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Missing required parameter in input: "ApplicationId"
```

I'm running `serverlessrepo==0.1.10`. But tried with `0.1.9` and got the same error.

The following line appears to fail to parse an application ID in `serverlessrepo.publish:publish_application`:

```python
application_id = parse_application_id(error_message)
```

**Comment by kolanos** [comment]
The `error_message` has no ARN in it. What I'm getting is:

``` 
Application with name my-test-sar-app already exists
```
